# font_family JetBrainsMono Nerd Font
# font_family Caskaydia Cove Nerd Font
font_family CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

# Optional: Nice visual tweaks
cursor_blink_interval 0.5
# Smoother scrolling
scrollback_lines 10000
wheel_scroll_multiplier 3

cursor_trail 8
cursor_trail_decay 0.15 0.4
cursor_trail_start_threshold 3

background_opacity 0.9

font_size 14.0

initial_window_width 95c
initial_window_height 35c

enable_image_protocol yes
enable_audio_bell no
confirm_os_window_close 0
# window
window_padding_width 5
window_margin_width 5
window_border_width 2px
# active_border_color #c1ced0
# inactive_border_color #718E92
enabled_layouts Tall, *

map kitty_mod+j third_window
map kitty_mod+l second_window
map kitty_mod+h first_window
map ctrl+shift+[ next_window


map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
allow_remote_control yes


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
